### ISSUE TITLE
Streamline & clearly define our feedback loop

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#127] opened 2021-01-18 20:26 UTC

**Comment by fharper** [comment] 2021-03-03 15:54
We removed the annoying chat box on the site & remove email everywhere except on the website. Still need to be clear about where to write what in terms of issues or features ideas.

**Comment by ferdi05** [comment] 2021-12-15 17:31
duplicate of #72

**Closed by ferdi05** 2021-12-15 17:31 UTC
Labels: type:community, P1
