### ISSUE TITLE
Tutorial "How to contribute to open-source"

### ISSUE THREAD

**Issue by curquiza** [meilisearch/devrel#159] opened 2021-01-28 13:12 UTC
Hello DevRel team! Sorry if it's not the place to ask this, feel free to close this issue in this case.

We all want our community to grow and to include as many people as possible. Contributors are a precious part of this community: they spread MeiliSearch love and they help us with the tool development.
However one of the first obstacles, when you want to contribute, is "I'm able to open an issue but I don't know how to contribute to opensource".
I was wondering if it would be worthy to **provide a tutorial to help people make their first contribution** so that they could come back and enjoy a great contributing experience with MeiliSearch 😁

As an integration team member, I would include a kind of friendly footer in our issues to encourage people to contribute, where this tutorial could be linked:

```
We would be glad to help you contribute to this repo, feel free to ask any question in this issue if anything is not clear.
Also, if you have never contributed to open source before, check out this tutorial. We would be happy to guide you through your first open-source contribution.
```
(This is not the definitive version, just an example)

For the moment, we only provide some steps in the CONTRIBUTING.md of each repo: https://github.com/meilisearch/integration-guides/blob/master/templates/CONTRIBUTING.md#how-to-contribute
However, I'm not sure this is enough. Tell me if it is from your POV. I can link this for the moment in my future issue footers.

_This idea comes from @bidoubiwa 😇_

**Comment by fharper** [comment] 2021-01-28 20:56
Unless I didn't understand correctly, it is already in the pipeline for Q1: see #17.

Also, in the future, we would like to create generic videos on how to be involved in OSS, not just for Meili, kinda generic tips.

**Comment by curquiza** [comment] 2021-02-01 12:21
@fharper, this could be indeed what I need! Thanks!
Sorry for my issue then, feel free to close it 🙂

**Comment by fharper** [comment] 2021-02-01 18:45
Duplicate of #17

**Closed by fharper** 2021-02-01 18:45 UTC
Labels: Community, documentation
