### ISSUE TITLE
Update your author profile on the blog

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#23] opened 2020-12-01 15:35 UTC
https://blog.meilisearch.com/ghost/#/staff/marin/

**Comment by fharper** [comment] 2021-01-05 20:27
You should add information in the bio at a minimum. It could be as simple as "I work on the core team at MeiliSearch" or a better bio Twitter style.

If you feel like sharing, it would be even more awesome to add your Twitter username, if you have one, your location (can be at the country level) and website if you have any.

![image](https://user-images.githubusercontent.com/1170989/103695256-405e9480-4f6a-11eb-96c3-f62289ebc6f1.png)

Thanks for taking 5 minutes so our community can see a little more about you :D

**Comment by fharper** [comment] 2021-04-14 20:24
Would be nice to be able to close this issue :D

**Comment by ferdi05** [comment] 2021-12-22 09:05
now a duplicate of #24

**Closed by ferdi05** 2021-12-22 09:05 UTC
Labels: type:community
