### ISSUE TITLE
Create a devrel KPI dashboard

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#95] opened 2021-01-07 22:31 UTC
Something to track feel good metrics in one place: github stars, documentation total views, slack community member numbers...

**Comment by fharper** [comment] 2021-01-12 21:54
I need to give it a closer look, but I may be able to create something with https://amplitude.com since we already use the tool

**Comment by ferdi05** [comment] 2021-12-28 10:04
Duplicate of #332, will close

**Closed by ferdi05** 2021-12-28 10:04 UTC
Labels: type:management, y2021-Q2, P1
