### ISSUE TITLE
Tutorial: Elasticsearch to MeiliSearch

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#145] opened 2021-01-21 21:07 UTC
Show people how to move their search from Elasticsearch to MeiliSearch

**Comment by react-learner** [comment] 2021-01-22 15:50
#147 : same goal but w/ Algolia

**Comment by ferdi05** [comment] 2022-06-27 16:40
duplicate of #354. closing this

**Closed by ferdi05** 2022-06-27 16:40 UTC
Labels: type:tutorials, P2
