### ISSUE TITLE
Evaluate Slack alternatives for our community

### ISSUE THREAD

**Issue by fharper** [meilisearch/devrel#36] opened 2020-12-09 20:03 UTC
We are using Slack right now for our community. It is working well, and the de factor for real-time communities discussions, but we already reached the limit on searchable messages with the free account (that are other limitations we may reach sooner than later, like apps integrations). For a community that will continue to grow, it is not scalable to move to another tier. 

I suggest to take a look at alternatives like [MatterMost](https://mattermost.com/) which is free and not limited when self-hosted. It will give our users a better search experience, and will look more professional since everyone is seeing this warning. On the other side, it may not bring as many people in our real-time chat community since they would need to install another app they may not already use.

It's not critical for now, just putting this here so we can start the discussion if it make sense or not, if it's a real issue or not, listing alternatives...

![](https://user-images.githubusercontent.com/1170989/101680593-e9c76e80-3a2e-11eb-8e9e-a7a1ae138a4f.png)

**Comment by fharper** [comment] 2021-03-03 15:35
The big problem of history with free plans will be solved... by using our own technology, so I don't see why we would need to change as right now Slack is fitting our needs.

**Comment by ferdi05** [comment] 2021-12-22 08:45
yet not implemented

**Comment by ferdi05** [comment] 2022-06-27 16:42
duplicate of #434. Closing this issue

**Closed by ferdi05** 2022-06-27 16:42 UTC
Labels: type:community, type:management, P4
